### ISSUE TITLE
Only creates modules and entity directory

### ISSUE THREAD

**Issue by YassineGherbi** [ndabAP/vuex-cli-scaffold#1]
Error: Error: ENOENT: no such file or directory, open './../lib/module.js'
    at ReadFileContext.fs.readFile [as callback] (/Users/yassine/Coding/personal/THEORIECURSUS/theoriecursusplanner/node_modules/vuex-cli-scaffold/src/helper/construct.js:16:22)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)

It does only create the module directory and entity directory

**Comment by ndabAP** [comment]
Thanks a lot. Correct directory is `../../lib/module.js`.
